"""value grade 3 dimensions

Revision ID: 00a82ba91945
Revises: 0a4144264e8b
Create Date: 2026-05-13 17:59:42.252013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00a82ba91945'
down_revision: Union[str, None] = '0a4144264e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle_participant', sa.Column('final_value_belief', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('cycle_participant', sa.Column('final_value_team', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('cycle_participant', sa.Column('final_value_growth', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.drop_column('cycle_participant', 'final_value_grade')
    op.add_column('evaluation', sa.Column('value_belief_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('evaluation', sa.Column('value_belief_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evaluation', sa.Column('value_team_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('evaluation', sa.Column('value_team_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evaluation', sa.Column('value_growth_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('evaluation', sa.Column('value_growth_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('evaluation', 'value_grade')
    op.drop_column('evaluation', 'value_example')
    op.add_column('peer_evaluation', sa.Column('value_belief_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('peer_evaluation', sa.Column('value_belief_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('peer_evaluation', sa.Column('value_team_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('peer_evaluation', sa.Column('value_team_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('peer_evaluation', sa.Column('value_growth_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('peer_evaluation', sa.Column('value_growth_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('peer_evaluation', 'value_grade')
    op.drop_column('peer_evaluation', 'value_example')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peer_evaluation', sa.Column('value_example', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('peer_evaluation', sa.Column('value_grade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True))
    op.drop_column('peer_evaluation', 'value_growth_example')
    op.drop_column('peer_evaluation', 'value_growth_grade')
    op.drop_column('peer_evaluation', 'value_team_example')
    op.drop_column('peer_evaluation', 'value_team_grade')
    op.drop_column('peer_evaluation', 'value_belief_example')
    op.drop_column('peer_evaluation', 'value_belief_grade')
    op.add_column('evaluation', sa.Column('value_example', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('evaluation', sa.Column('value_grade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True))
    op.drop_column('evaluation', 'value_growth_example')
    op.drop_column('evaluation', 'value_growth_grade')
    op.drop_column('evaluation', 'value_team_example')
    op.drop_column('evaluation', 'value_team_grade')
    op.drop_column('evaluation', 'value_belief_example')
    op.drop_column('evaluation', 'value_belief_grade')
    op.add_column('cycle_participant', sa.Column('final_value_grade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True))
    op.drop_column('cycle_participant', 'final_value_growth')
    op.drop_column('cycle_participant', 'final_value_team')
    op.drop_column('cycle_participant', 'final_value_belief')
    # ### end Alembic commands ###
