"""add calibration and approval

Revision ID: 0154822c38fa
Revises: ff927545539d
Create Date: 2026-05-12 13:25:10.644002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0154822c38fa'
down_revision: Union[str, None] = 'ff927545539d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('hr_approver_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(), nullable=True),
    sa.Column('hr_comment', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('ceo_approver_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ceo_approved_at', sa.DateTime(), nullable=True),
    sa.Column('ceo_comment', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('rejected_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_approval_cycle_id'), 'cycle_approval', ['cycle_id'], unique=True)
    op.create_index(op.f('ix_cycle_approval_status'), 'cycle_approval', ['status'], unique=False)
    op.create_table('calibration_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operator_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('field_changed', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_record_created_at'), 'calibration_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_calibration_record_cycle_id'), 'calibration_record', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_calibration_record_user_id'), 'calibration_record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibration_record_user_id'), table_name='calibration_record')
    op.drop_index(op.f('ix_calibration_record_cycle_id'), table_name='calibration_record')
    op.drop_index(op.f('ix_calibration_record_created_at'), table_name='calibration_record')
    op.drop_table('calibration_record')
    op.drop_index(op.f('ix_cycle_approval_status'), table_name='cycle_approval')
    op.drop_index(op.f('ix_cycle_approval_cycle_id'), table_name='cycle_approval')
    op.drop_table('cycle_approval')
    # ### end Alembic commands ###
