"""add cycle mode switches and stage_json column

Revision ID: 0a4144264e8b
Revises: 4e88d9614e2d
Create Date: 2026-05-12 16:34:18.118785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a4144264e8b'
down_revision: Union[str, None] = '4e88d9614e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_cycle', sa.Column('enable_self_eval', sa.Boolean(), nullable=False))
    op.add_column('performance_cycle', sa.Column('enable_peer_eval', sa.Boolean(), nullable=False))
    op.add_column('performance_cycle', sa.Column('enable_calibration', sa.Boolean(), nullable=False))
    op.add_column('performance_cycle', sa.Column('enable_feedback', sa.Boolean(), nullable=False))
    op.add_column('performance_cycle', sa.Column('stage_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_cycle', 'stage_json')
    op.drop_column('performance_cycle', 'enable_feedback')
    op.drop_column('performance_cycle', 'enable_calibration')
    op.drop_column('performance_cycle', 'enable_peer_eval')
    op.drop_column('performance_cycle', 'enable_self_eval')
    # ### end Alembic commands ###
