"""add_objective_cycle_participant

Revision ID: 124515811db3
Revises: 1b1a7e062625
Create Date: 2026-06-29 19:16:03.292926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '124515811db3'
down_revision: Union[str, None] = '1b1a7e062625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective_cycle_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leader_userid_snapshot', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_name_snapshot', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['objective_cycle_id'], ['objective_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_cycle_participant_objective_cycle_id'), 'objective_cycle_participant', ['objective_cycle_id'], unique=False)
    op.create_index(op.f('ix_objective_cycle_participant_status'), 'objective_cycle_participant', ['status'], unique=False)
    op.create_index(op.f('ix_objective_cycle_participant_user_id'), 'objective_cycle_participant', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objective_cycle_participant_user_id'), table_name='objective_cycle_participant')
    op.drop_index(op.f('ix_objective_cycle_participant_status'), table_name='objective_cycle_participant')
    op.drop_index(op.f('ix_objective_cycle_participant_objective_cycle_id'), table_name='objective_cycle_participant')
    op.drop_table('objective_cycle_participant')
    # ### end Alembic commands ###
