"""add_employee_type_to_user

Revision ID: 1fa2247f205e
Revises: 4f0818179ab0
Create Date: 2026-06-26 10:13:23.562951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1fa2247f205e'
down_revision: Union[str, None] = '4f0818179ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('employee_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'employee_type')
    # ### end Alembic commands ###
