"""add probation plan

Revision ID: 40f5265b3aec
Revises: a088a1294289
Create Date: 2026-06-24 18:59:28.361566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40f5265b3aec'
down_revision: Union[str, None] = 'a088a1294289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probation_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('probation_months', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('objective_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('objective_reviewed_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('objective_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_comment', sa.Text(), nullable=True),
    sa.Column('evaluation_result', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('evaluator_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('extended_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('extended_at', sa.DateTime(), nullable=True),
    sa.Column('extension_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probation_plan_user_id'), 'probation_plan', ['user_id'], unique=False)
    op.create_table('probation_objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('measure_criteria', sa.Text(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['probation_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probation_objective_plan_id'), 'probation_objective', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_probation_objective_plan_id'), table_name='probation_objective')
    op.drop_table('probation_objective')
    op.drop_index(op.f('ix_probation_plan_user_id'), table_name='probation_plan')
    op.drop_table('probation_plan')
    # ### end Alembic commands ###
