"""add_historical_objective

Revision ID: 4c3b8a3aeab0
Revises: c5ecc433a069
Create Date: 2026-08-02 16:05:18.532836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4c3b8a3aeab0'
down_revision: Union[str, None] = 'c5ecc433a069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('measure_criteria', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_objective_cycle_name'), 'historical_objective', ['cycle_name'], unique=False)
    op.create_index(op.f('ix_historical_objective_user_id'), 'historical_objective', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_objective_user_id'), table_name='historical_objective')
    op.drop_index(op.f('ix_historical_objective_cycle_name'), table_name='historical_objective')
    op.drop_table('historical_objective')
    # ### end Alembic commands ###
