"""add feedback_record

Revision ID: 4e88d9614e2d
Revises: 0154822c38fa
Create Date: 2026-05-12 13:50:18.567697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e88d9614e2d'
down_revision: Union[str, None] = '0154822c38fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('interviewer_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('next_goals', sa.Text(), nullable=True),
    sa.Column('confirm_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('dispute_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'user_id', name='uq_feedback_per_user_cycle')
    )
    op.create_index(op.f('ix_feedback_record_confirm_status'), 'feedback_record', ['confirm_status'], unique=False)
    op.create_index(op.f('ix_feedback_record_cycle_id'), 'feedback_record', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_feedback_record_user_id'), 'feedback_record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_record_user_id'), table_name='feedback_record')
    op.drop_index(op.f('ix_feedback_record_cycle_id'), table_name='feedback_record')
    op.drop_index(op.f('ix_feedback_record_confirm_status'), table_name='feedback_record')
    op.drop_table('feedback_record')
    # ### end Alembic commands ###
