"""v0.9 initial schema

Revision ID: a088a1294289
Revises: 
Create Date: 2026-05-11 17:46:48.719945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a088a1294289'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('measure_criteria', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_cycle_id'), 'objective', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_objective_user_id'), 'objective', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objective_user_id'), table_name='objective')
    op.drop_index(op.f('ix_objective_cycle_id'), table_name='objective')
    op.drop_table('objective')
    # ### end Alembic commands ###
