"""v0.9 initial schema

Revision ID: a088a1294289
Revises: 
Create Date: 2026-06-22 13:30:24.678367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a088a1294289'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_operator_userid'), 'audit_log', ['operator_userid'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wecom_dept_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('leader_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_wecom_dept_id'), 'department', ['wecom_dept_id'], unique=True)
    op.create_table('export_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('export_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('filter_data', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_log_created_at'), 'export_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_export_log_operator_userid'), 'export_log', ['operator_userid'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_status'), 'notification_log', ['status'], unique=False)
    op.create_index(op.f('ix_notification_log_target_userid'), 'notification_log', ['target_userid'], unique=False)
    op.create_table('performance_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('enable_self_eval', sa.Boolean(), nullable=False),
    sa.Column('enable_peer_eval', sa.Boolean(), nullable=False),
    sa.Column('enable_calibration', sa.Boolean(), nullable=False),
    sa.Column('enable_feedback', sa.Boolean(), nullable=False),
    sa.Column('stage_json', sa.JSON(), nullable=True),
    sa.Column('exclusion_rules', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_cycle_status'), 'performance_cycle', ['status'], unique=False)
    op.create_table('cycle_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('hr_approver_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(), nullable=True),
    sa.Column('hr_comment', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('ceo_approver_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ceo_approved_at', sa.DateTime(), nullable=True),
    sa.Column('ceo_comment', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('rejected_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_approval_cycle_id'), 'cycle_approval', ['cycle_id'], unique=True)
    op.create_index(op.f('ix_cycle_approval_status'), 'cycle_approval', ['status'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wecom_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('leader_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('hrbp_scope_dept_ids', sa.JSON(), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('confirm_date', sa.Date(), nullable=True),
    sa.Column('probation', sa.Integer(), nullable=True),
    sa.Column('employee_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_leader_userid'), 'user', ['leader_userid'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_index(op.f('ix_user_wecom_userid'), 'user', ['wecom_userid'], unique=True)
    op.create_table('anonymous_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('perf_score', sa.Float(), nullable=True),
    sa.Column('value_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_feedback_author_user_id'), 'anonymous_feedback', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_anonymous_feedback_cycle_id'), 'anonymous_feedback', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_anonymous_feedback_target_user_id'), 'anonymous_feedback', ['target_user_id'], unique=False)
    op.create_table('calibration_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operator_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('field_changed', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_record_created_at'), 'calibration_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_calibration_record_cycle_id'), 'calibration_record', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_calibration_record_user_id'), 'calibration_record', ['user_id'], unique=False)
    op.create_table('cycle_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leader_userid_snapshot', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_name_snapshot', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('final_perf_score', sa.Float(), nullable=True),
    sa.Column('final_perf_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('final_value_belief', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('final_value_team', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('final_value_growth', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='参与人维度进度跟踪'
    )
    op.create_index(op.f('ix_cycle_participant_cycle_id'), 'cycle_participant', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_cycle_participant_status'), 'cycle_participant', ['status'], unique=False)
    op.create_index(op.f('ix_cycle_participant_user_id'), 'cycle_participant', ['user_id'], unique=False)
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('eval_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('perf_score', sa.Float(), nullable=True),
    sa.Column('perf_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('value_belief_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('value_belief_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_team_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('value_team_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_growth_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('value_growth_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key_results', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'user_id', 'eval_type', name='uq_eval_unique')
    )
    op.create_index(op.f('ix_evaluation_cycle_id'), 'evaluation', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_evaluation_eval_type'), 'evaluation', ['eval_type'], unique=False)
    op.create_index(op.f('ix_evaluation_status'), 'evaluation', ['status'], unique=False)
    op.create_index(op.f('ix_evaluation_user_id'), 'evaluation', ['user_id'], unique=False)
    op.create_table('feedback_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('interviewer_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('next_goals', sa.Text(), nullable=True),
    sa.Column('confirm_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('dispute_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'user_id', name='uq_feedback_per_user_cycle')
    )
    op.create_index(op.f('ix_feedback_record_confirm_status'), 'feedback_record', ['confirm_status'], unique=False)
    op.create_index(op.f('ix_feedback_record_cycle_id'), 'feedback_record', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_feedback_record_user_id'), 'feedback_record', ['user_id'], unique=False)
    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('measure_criteria', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_cycle_id'), 'objective', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_objective_user_id'), 'objective', ['user_id'], unique=False)
    op.create_table('objective_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_objectives', sa.JSON(), nullable=True),
    sa.Column('new_objectives', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('requested_by_userid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_revision_cycle_id'), 'objective_revision', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_objective_revision_user_id'), 'objective_revision', ['user_id'], unique=False)
    op.create_table('peer_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_user_id', sa.Integer(), nullable=False),
    sa.Column('perf_score', sa.Float(), nullable=True),
    sa.Column('perf_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('value_belief_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('value_belief_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_team_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('value_team_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_growth_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('value_growth_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'target_user_id', 'evaluator_user_id', name='uq_peer_evaluation')
    )
    op.create_index(op.f('ix_peer_evaluation_cycle_id'), 'peer_evaluation', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_peer_evaluation_evaluator_user_id'), 'peer_evaluation', ['evaluator_user_id'], unique=False)
    op.create_index(op.f('ix_peer_evaluation_status'), 'peer_evaluation', ['status'], unique=False)
    op.create_index(op.f('ix_peer_evaluation_target_user_id'), 'peer_evaluation', ['target_user_id'], unique=False)
    op.create_table('peer_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('invitee_user_id', sa.Integer(), nullable=False),
    sa.Column('peer_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('proposed_by', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['peer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'invitee_user_id', 'peer_user_id', name='uq_peer_invitation')
    )
    op.create_index(op.f('ix_peer_invitation_cycle_id'), 'peer_invitation', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_peer_invitation_invitee_user_id'), 'peer_invitation', ['invitee_user_id'], unique=False)
    op.create_index(op.f('ix_peer_invitation_peer_user_id'), 'peer_invitation', ['peer_user_id'], unique=False)
    op.create_index(op.f('ix_peer_invitation_status'), 'peer_invitation', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQL 不允许删除外键正在使用的索引，因此 downgrade 直接 drop_table
    # （drop table 会自动清理索引和外键约束），并先删引用表、后删被引用表。
    op.drop_table('peer_invitation')
    op.drop_table('peer_evaluation')
    op.drop_table('objective_revision')
    op.drop_table('objective')
    op.drop_table('feedback_record')
    op.drop_table('evaluation')
    op.drop_table('cycle_participant')
    op.drop_table('calibration_record')
    op.drop_table('anonymous_feedback')
    op.drop_table('cycle_approval')
    op.drop_table('user')
    op.drop_table('department')
    op.drop_table('performance_cycle')
    op.drop_table('notification_log')
    op.drop_table('export_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
