"""add hrbp_scope_dept_ids

Revision ID: b76d8ace606f
Revises: a088a1294289
Create Date: 2026-05-11 18:03:39.936763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b76d8ace606f'
down_revision: Union[str, None] = 'a088a1294289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hrbp_scope_dept_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hrbp_scope_dept_ids')
    # ### end Alembic commands ###
