"""add peer models

Revision ID: ff927545539d
Revises: b76d8ace606f
Create Date: 2026-05-11 18:31:47.574102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff927545539d'
down_revision: Union[str, None] = 'b76d8ace606f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('perf_score', sa.Float(), nullable=True),
    sa.Column('value_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_feedback_author_user_id'), 'anonymous_feedback', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_anonymous_feedback_cycle_id'), 'anonymous_feedback', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_anonymous_feedback_target_user_id'), 'anonymous_feedback', ['target_user_id'], unique=False)
    op.create_table('peer_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_user_id', sa.Integer(), nullable=False),
    sa.Column('perf_score', sa.Float(), nullable=True),
    sa.Column('perf_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('value_grade', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('value_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'target_user_id', 'evaluator_user_id', name='uq_peer_evaluation')
    )
    op.create_index(op.f('ix_peer_evaluation_cycle_id'), 'peer_evaluation', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_peer_evaluation_evaluator_user_id'), 'peer_evaluation', ['evaluator_user_id'], unique=False)
    op.create_index(op.f('ix_peer_evaluation_status'), 'peer_evaluation', ['status'], unique=False)
    op.create_index(op.f('ix_peer_evaluation_target_user_id'), 'peer_evaluation', ['target_user_id'], unique=False)
    op.create_table('peer_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('invitee_user_id', sa.Integer(), nullable=False),
    sa.Column('peer_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('proposed_by', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycle.id'], ),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['peer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'invitee_user_id', 'peer_user_id', name='uq_peer_invitation')
    )
    op.create_index(op.f('ix_peer_invitation_cycle_id'), 'peer_invitation', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_peer_invitation_invitee_user_id'), 'peer_invitation', ['invitee_user_id'], unique=False)
    op.create_index(op.f('ix_peer_invitation_peer_user_id'), 'peer_invitation', ['peer_user_id'], unique=False)
    op.create_index(op.f('ix_peer_invitation_status'), 'peer_invitation', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_invitation_status'), table_name='peer_invitation')
    op.drop_index(op.f('ix_peer_invitation_peer_user_id'), table_name='peer_invitation')
    op.drop_index(op.f('ix_peer_invitation_invitee_user_id'), table_name='peer_invitation')
    op.drop_index(op.f('ix_peer_invitation_cycle_id'), table_name='peer_invitation')
    op.drop_table('peer_invitation')
    op.drop_index(op.f('ix_peer_evaluation_target_user_id'), table_name='peer_evaluation')
    op.drop_index(op.f('ix_peer_evaluation_status'), table_name='peer_evaluation')
    op.drop_index(op.f('ix_peer_evaluation_evaluator_user_id'), table_name='peer_evaluation')
    op.drop_index(op.f('ix_peer_evaluation_cycle_id'), table_name='peer_evaluation')
    op.drop_table('peer_evaluation')
    op.drop_index(op.f('ix_anonymous_feedback_target_user_id'), table_name='anonymous_feedback')
    op.drop_index(op.f('ix_anonymous_feedback_cycle_id'), table_name='anonymous_feedback')
    op.drop_index(op.f('ix_anonymous_feedback_author_user_id'), table_name='anonymous_feedback')
    op.drop_table('anonymous_feedback')
    # ### end Alembic commands ###
